# Generated by Django 4.2.18 on 2025-02-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_mlmodel_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='tip1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='tip2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='tip3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
