# Generated by Django 4.2.18 on 2025-02-12 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee', '0003_mlmodel_tip1_mlmodel_tip2_mlmodel_tip3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('tip1', models.TextField(blank=True, null=True)),
                ('tip2', models.TextField(blank=True, null=True)),
                ('tip3', models.TextField(blank=True, null=True)),
                ('users', models.ManyToManyField(related_name='metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
