# Generated by Django 4.2.18 on 2025-02-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='workspace_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
