# Generated by Django 4.2.18 on 2025-04-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_metric_workspace_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('graph', 'График'), ('report', 'Отчёт'), ('forecast', 'Прогноз')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='old_reports/')),
                ('filters', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
